version: "3.8"

services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: not1c1asGT!
      POSTGRES_DB: dbnoticias
    ports:
      - "5432:5432"
